version: '3'

networks:
  discord-botti:
    driver: bridge

services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: HamburjareDB
      MYSQL_USER: hamburjare
      MYSQL_PASSWORD: hamburjare
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped
    networks:
      - discord-botti

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - discord-botti
    
  app:
    build: .
    depends_on:
      - db
    env_file: .env
    restart: unless-stopped
    networks:
      - discord-botti
    
volumes:
  dbdata:

